# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: F:\Coding\sentiment_analysis_of_social_media_data

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to train data directory
train_data_dir: ${paths.root_dir}/data/train

# path to train data directory
val_data_dir: ${paths.root_dir}/data/valid

# path to train data directory
test_data_dir: ${paths.root_dir}/data/test

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

